led_count: 30       # Number of LED pixels
led_pin: 13         # GPIO pin connected to the pixels (must support PWM!)
led_freq_hs: 800000   # LED signal frequency in hertz (usually 800khz)
led_dma: 10         # DMA channel to use for generating signal (try 10)
led_brightness: 255 # Set to 0 for darkest and 255 for brightest
led_invert: True    # True to invert the signal (when using NPN transistor level shift)
led_channel: 1