#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        gear_ratio: 5.4375
        offset_position: 0
        home_position: 0.0
        limit_position_min: -2.966  # joint limit min
        limit_position_max: 2.966   # joint limit max
        direction: -1
        max_effort: 110

    stepper_2:
        gear_ratio: 8.5625
        offset_position: 0
        home_position: 0.5
        limit_position_min: -2.09
        limit_position_max: 0.61
        direction: -1
        max_effort: 130
        
    stepper_3:
        gear_ratio: 7.6875
        offset_position: 0
        home_position: -1.25
        limit_position_min: -1.34
        limit_position_max: 1.57
        direction: -1
        max_effort: 120

