#
#  Stepper caracteristics for Ned's hardware
#

steppers:
    stepper_1:
        id: 2
        # gear_ratio, max_effort and micro_steps not used for ttl steppers
        motor_ratio: 0.0872
        # assembly offset position (rad)
        offset_position: -2.966
        # home position (rad)
        home_position: 0.0
        limit_position_min: -2.966  # joint limit min
        limit_position_max: 2.966   # joint limit max
        # assembly direction (1 or -1)
        direction: 1
        # rule is a_max = a_1 * 3
        #         d_max = d_1 * 3
        #         v_max = v_1 * 3
        #         d_max = a_max + 200
        v_start: 0
        a_1: 1260
        v_1: 500
        a_max: 2500
        v_max: 1500
        d_max: 2500
        d_1: 1228
        v_stop: 20

    stepper_2:
        id: 3
        motor_ratio: 0.0868
        offset_position: 0.61
        home_position: 0.5
        limit_position_max: 0.61
        limit_position_min: -2.09
        direction: -1
        # rule is a_max = a_1 * 3
        #         d_max = d_1 * 3
        #         v_max = v_1 * 3
        #         d_max = a_max + 100
        v_start: 0
        a_1: 860
        v_1: 300
        a_max: 1400
        v_max: 1000
        d_max: 1400
        d_1: 860
        v_stop: 20
        
    stepper_3:
        id: 4
        motor_ratio: 0.0868
        offset_position: -1.34
        home_position: -1.25
        limit_position_min: -1.34
        limit_position_max: 1.57
        direction: 1
        # rule is a_max = a_1 * 3
        #         d_max = d_1 * 3
        #         v_max = v_1 * 3
        #         d_max = a_max + 100
        v_start: 0
        a_1: 915
        v_1: 400
        a_max: 1700
        v_max: 1200
        d_max: 1700
        d_1: 983
        v_stop: 20
