#
#  Stepper caracteristics for Ned's hardware
#
steppers:
    stepper_1:
        gear_ratio: 6.0625
        offset_position: 0
        home_position: 0.0
        limit_position_min: -3.05433  # joint limit min
        limit_position_max: 3.05433   # joint limit max
        direction: -1
        max_effort: 90

    stepper_2:
        gear_ratio: 8.3125
        offset_position: 0
        home_position: 0.5
        limit_position_max: 0.640187
        limit_position_min: -1.91
        direction: -1
        max_effort: 130
        
    stepper_3:
        gear_ratio: 7.875
        offset_position: 0
        home_position: -1.25
        limit_position_min: -1.397485
        limit_position_max: 1.57
        direction: 1
        max_effort: 120

